[tool.poetry]
name = "brain_structure_tree_generator"
version = "0.1.0"
description = ""
authors = ["Can H. Tartanoglu <canhtart@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
Wikipedia-API = "^0.5.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

